version: '3'
services:
  db:
    image: postgres:15
    container_name: booking_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: booking_dashboard
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mimo7979
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: